"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { CalendarDays, Compass, ArrowRight, Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { TripStorageService } from "@/services/trip-storage.service"
import { Trip } from "@/types"

export default function ItinerariesPage() {
  const [trips, setTrips] = useState<Trip[]>([])

  useEffect(() => {
    setTrips(TripStorageService.getAllTrips())
  }, [])

  return (
    <div className="space-y-8 pb-16">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border/60 pb-6">
        <div>
          <div className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-primary mb-1">
            <CalendarDays className="h-3.5 w-3.5" />
            <span>Itinerary Center</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">Saved Daily Itineraries</h1>
          <p className="text-xs sm:text-sm text-muted-foreground mt-0.5">
            Review and adjust day-by-day itineraries generated by our intelligent engine.
          </p>
        </div>

        <Button asChild size="lg" className="rounded-xl font-bold gap-2 shadow-md">
          <Link href="/app/plan">
            <Plus className="h-4 w-4" />
            <span>Generate New Itinerary</span>
          </Link>
        </Button>
      </div>

      {trips.length === 0 ? (
        <div className="p-12 text-center rounded-2xl border border-dashed border-border bg-muted/20 my-8">
          <CalendarDays className="h-10 w-10 text-muted-foreground mx-auto mb-3" />
          <h3 className="text-base font-bold">No generated itineraries yet</h3>
          <p className="text-xs text-muted-foreground mt-1 max-w-sm mx-auto">
            Use our multi-step planner to create customized day-wise itineraries tailored to your budget and travel pace.
          </p>
          <Button asChild size="sm" className="mt-4 font-bold">
            <Link href="/app/plan">Plan a Trip</Link>
          </Button>
        </div>
      ) : (
        <div className="space-y-6">
          {trips.map((trip) => (
            <Card key={trip.id} className="p-6 border-border/60 shadow-xs space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-border/40 pb-4">
                <div>
                  <Badge variant="secondary" className="mb-1 text-[10px] uppercase font-bold">
                    {trip.numDays}-Day Plan
                  </Badge>
                  <h3 className="text-lg font-bold">{trip.title}</h3>
                  <div className="text-xs text-muted-foreground">
                    Destination: {trip.destinationName} • Starting from {trip.originName}
                  </div>
                </div>

                <Button asChild size="sm" className="font-bold text-xs gap-1.5">
                  <Link href={`/app/trips/${trip.id}`}>
                    <span>Open Full Workspace</span>
                    <ArrowRight className="h-3.5 w-3.5" />
                  </Link>
                </Button>
              </div>

              {trip.itinerary?.days && (
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  {trip.itinerary.days.slice(0, 3).map((day: any) => (
                    <div key={day.dayNumber} className="p-3 rounded-xl bg-muted/40 border border-border/60 text-xs space-y-1">
                      <div className="font-bold text-primary">{day.title}</div>
                      <div className="text-muted-foreground text-[11px]">
                        {day.activities.length} activities scheduled
                      </div>
                      <div className="text-[10px] text-muted-foreground">
                        Est: ₹{day.estimatedDayCostInr.toLocaleString()}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
